# Generated by Django 5.2 on 2025-04-04 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traffic', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='embedding',
            field=models.JSONField(default=None),
            preserve_default=False,
        ),
    ]
